### ISSUE TITLE
How to obtain API_KEY and API_SECRET

### ISSUE THREAD

**Issue by shreyasgp** [WazirX/wazirx-connector-python#1]
How to generate API Keys to place orders and perform actions on other account specific endpoints.
It is not mentioned anywhere in the docs on how to obtain the keys.

**Comment by VinayChaudhari1996** [comment]
Yeah same question and how to get historical transaction details ? 

1) transaction fees 
2) base amount
3) buy 
4) sell
5) overall profit
6) overall loss 

Thanks

**Comment by swagsasi** [comment]
I mailed them yesterday and the reply was:
"At the moment, we do not have a private API available at the moment but we will be building this out later as a part of the platform development."

If the private API is not developed, then why there is a documentation on how to use it?
[](https://wazirx.github.io/)
![Example](https://user-images.githubusercontent.com/54409398/139030325-fbc573e7-45da-44cc-a0d5-a3a0275a3dd6.png)

**Comment by VinayChaudhari1996** [comment]
@swagsasi  exactly ! 
It seems something is fishy.

**Comment by coder-life-web** [comment]
Please let us know how to obtain API_KEY and API_SECRET

**Comment by swagsasi** [comment]
Update: I sent them the above image and asked a clarification. Their reply was:

"Apologies for the late reply!

We do apologize for the inconvenience, however currently we haven't provided access to  any of the APIs as of now currently we are working on adding this option.

Once we launch this option we will announce it in our channels."

So, I guess that API is in beta stage. We may get access soon.

**Comment by lal-r** [comment]
> How to generate API Keys to place orders and perform actions on other account-specific endpoints. It is not mentioned anywhere in the docs on how to obtain the keys.?
Ans: Go to https://wazirx.com/settings/keys where you can create and manage API keys.

**Comment by dibyajitgoswamidg** [comment]
Keys can be created [here](https://wazirx.com/settings/keys)

Follow this [Link](https://docs.wazirx.com/) for the updated documentation.
