### ISSUE TITLE
Please provide more Examples of How to use - Wazirx Python Connecter

### ISSUE THREAD

**Issue by lal-r** [WazirX/wazirx-connector-python#3]
Give examples of how to:
1. Buy _(Already given in Readme.md_)
2. Sell
3. Cancel order
4. Check order status
5. Fetch account details

Sample **code snippets** will help beginner developers like myself to use Wazirx API easily.

**Comment by dibyajitgoswamidg** [comment]
For other methods follow this - [LINK](https://github.com/WazirX/wazirx-connector-python/blob/master/wazirx_sapi_client/rest/api_mapper.json)

For the parameters follow this - [LINK](https://docs.wazirx.com/)
