### ISSUE TITLE
Websocket connection error 1009

### ISSUE THREAD

**Issue by coder-life-web** [WazirX/wazirx-connector-python#5]
When I try to connect to websocket with multiple ticker symbols streams, i m getting connection faild with error code 1009.

Is there any limitation in the number of streams in one webservice connection?

**Comment by lal-r** [comment]
Visit <https://docs.wazirx.com/#error-messages> -For more details regarding error codes (Websockets).
#### Limit reached error | Example
`{"data":{"code":429,"message":"Too many request: max streams subscription limit reached","id":0}`

**Comment by dibyajitgoswamidg** [comment]
I feel this has been resolved, closing this. please reopen if still exists.
