### ISSUE TITLE
429 Error even after using sleep for 5 seconds

### ISSUE THREAD

**Issue by hanishche** [WazirX/wazirx-connector-python#7]
HI I am trying to pull live data for below coins and its throwing 429 error even though i m using 5 seconds sleep time between each crypto. As far as i can find from documentation that there is a limit of 10/sec. I would like to knoe the limits on all of the endpoints. So that i dont spam. Thanks

crypto=['maticinr','manainr','xrpinr','dogeinr','adainr','batinr','chrinr','phainr','enjinr','cotiinr','ctsiinr','dockinr']

def live_price(crypto,iter_error,client):
    try:
        client = Client()
        live_response,live_price=client.send("ticker",{"symbol":crypto})
        live_price=pd.DataFrame(live_price,index=range(0,1))
        live_price['date_time']=pd.to_datetime(live_price['at'], unit='ms').apply(lambda x: (x+timedelta(minutes = 330)))
        live_price.to_sql(crypto, if_exists='append', con=engine)
        iter_error=0
        time.sleep(5)
    except BaseException as e:
        iter_error+=1
        time.sleep(5)
        print(e,crypto)
    return iter_error

**Comment by earthshakira** [comment]
@dibyajitgoswamidg  Hi! can work on this issue ?

**Comment by dibyajitgoswamidg** [comment]
Refer this for [rate limits](https://docs.google.com/document/d/1NbaMs_EJFskcfHKTGP7kxf6EFGy_h2eDG34qrO_hzsw)
I feel this has already been resolved! Please open if its still there.
