### ISSUE TITLE
Valid Api Name Required error occurs for funds & account API names

### ISSUE THREAD

**Issue by digiajay** [WazirX/wazirx-connector-python#8]
I see other endpoints like historical_trades, open_orders, all_orders are responding.  But funds and accounts are raising exceptions as below

`Traceback (most recent call last):
  File "/Users/digiajay/Documents/Projects/Bitbucket/aj_wazirx/strategy_1.py", line 37, in <module>
    funds = (client.send('account',{"timestamp": int(time.time() * 1000)}))
  File "/Users/digiajay/Documents/Projects/Bitbucket/aj_wazirx/wazirx_sapi_client/rest/client.py", line 35, in send
    raise BaseException("Valid Api Name Required")
BaseException: Valid Api Name Required`

**Comment by MaheshAravindV** [comment]
Look inside the api_mapper.json, you should use "funds_info" for funds and "account_info" for account info.

**Comment by dibyajitgoswamidg** [comment]
I think this issue has been resolved. Closing this issue
